/** Canonical Hostiggo amenity enum + fuzzy mapping from OTA free-text. */
export const AMENITIES = [
  "wifi",
  "air_conditioning",
  "heating",
  "kitchen",
  "washer",
  "dryer",
  "free_parking",
  "paid_parking",
  "pool",
  "hot_tub",
  "gym",
  "tv",
  "workspace",
  "breakfast",
  "hair_dryer",
  "iron",
  "essentials",
  "smoke_alarm",
  "carbon_monoxide_alarm",
  "first_aid_kit",
  "fire_extinguisher",
  "pets_allowed",
  "smoking_allowed",
  "elevator",
  "power_backup",
  "hot_water",
  "geyser",
  "balcony",
  "garden",
  "mountain_view",
  "sea_view",
  "wheelchair_accessible",
  "self_check_in",
  "security_cameras",
  "housekeeping",
] as const;

export type Amenity = (typeof AMENITIES)[number];

const MAP: [RegExp, Amenity][] = [
  [/wi[\s-]?fi|wireless internet|internet/i, "wifi"],
  [/air.?condition|\bac\b|a\/c/i, "air_conditioning"],
  [/heating|heater|radiator/i, "heating"],
  [/kitchen|kitchenette/i, "kitchen"],
  [/washing machine|washer/i, "washer"],
  [/dryer|tumble dry/i, "dryer"],
  [/free.*parking|complimentary parking/i, "free_parking"],
  [/paid.*parking|parking \(.*charge/i, "paid_parking"],
  [/\bparking\b/i, "free_parking"],
  [/swimming pool|\bpool\b/i, "pool"],
  [/hot tub|jacuzzi|jacuzzi/i, "hot_tub"],
  [/\bgym\b|fitness/i, "gym"],
  [/\btv\b|television|cable/i, "tv"],
  [/workspace|work desk|dedicated desk/i, "workspace"],
  [/breakfast/i, "breakfast"],
  [/hair.?dryer/i, "hair_dryer"],
  [/\biron\b|ironing/i, "iron"],
  [/essentials|towels|linen/i, "essentials"],
  [/smoke (alarm|detector)/i, "smoke_alarm"],
  [/carbon monoxide/i, "carbon_monoxide_alarm"],
  [/first aid/i, "first_aid_kit"],
  [/fire extinguisher/i, "fire_extinguisher"],
  [/pets? allowed|pet friendly/i, "pets_allowed"],
  [/smoking allowed/i, "smoking_allowed"],
  [/elevator|lift/i, "elevator"],
  [/power backup|generator|inverter/i, "power_backup"],
  [/hot water/i, "hot_water"],
  [/geyser/i, "geyser"],
  [/balcony|terrace/i, "balcony"],
  [/garden|lawn/i, "garden"],
  [/mountain view|hill view|valley view/i, "mountain_view"],
  [/sea view|ocean view|beach view/i, "sea_view"],
  [/wheelchair|accessible/i, "wheelchair_accessible"],
  [/self check.?in|lockbox|smart lock|keypad/i, "self_check_in"],
  [/security camera|cctv/i, "security_cameras"],
  [/housekeeping|daily cleaning/i, "housekeeping"],
];

export function normalizeAmenity(raw: string): Amenity | null {
  const s = raw.toLowerCase().trim();
  if ((AMENITIES as readonly string[]).includes(s)) return s as Amenity;
  for (const [re, a] of MAP) if (re.test(s)) return a;
  return null;
}
