-- Seed external_taxonomy_map with common Airbnb values -> Hostiggo enum slugs.
-- `internal_id` is left NULL here — run 003 (or your own script) to fill it by
-- joining internal_slug against property_types / stay_types / amenities.

set search_path to hostiggo_testing_schema, public;

insert into external_taxonomy_map (source, entity_type, external_value, internal_slug) values
  -- property types
  ('airbnb','property_type','Entire home',        'house'),
  ('airbnb','property_type','House',              'house'),
  ('airbnb','property_type','Apartment',          'apartment'),
  ('airbnb','property_type','Rental unit',        'apartment'),
  ('airbnb','property_type','Condo',              'apartment'),
  ('airbnb','property_type','Villa',              'villa'),
  ('airbnb','property_type','Cabin',              'cabin'),
  ('airbnb','property_type','Cottage',            'cottage'),
  ('airbnb','property_type','Bungalow',           'bungalow'),
  ('airbnb','property_type','Farm stay',          'farm_stay'),
  ('airbnb','property_type','Guesthouse',         'guesthouse'),
  ('airbnb','property_type','Guest suite',        'guesthouse'),
  ('airbnb','property_type','Bed and breakfast',  'homestay'),
  ('airbnb','property_type','Boutique hotel',     'boutique_hotel'),
  ('airbnb','property_type','Hostel',             'hostel'),
  ('airbnb','property_type','Houseboat',          'houseboat'),
  ('airbnb','property_type','Boat',               'boat'),
  ('airbnb','property_type','Treehouse',          'treehouse'),
  ('airbnb','property_type','Dome',               'dome'),
  ('airbnb','property_type','Yurt',               'yurt'),
  ('airbnb','property_type','Cave',               'cave'),
  ('airbnb','property_type','Tent',               'tent'),
  ('airbnb','property_type','Camper/RV',          'other'),
  -- stay types
  ('airbnb','stay_type','Entire home/apt', 'entire_property'),
  ('airbnb','stay_type','Entire place',    'entire_property'),
  ('airbnb','stay_type','Private room',    'private_room'),
  ('airbnb','stay_type','Hotel room',      'private_room'),
  ('airbnb','stay_type','Shared room',     'shared_space'),
  -- amenities
  ('airbnb','amenity','Wifi',                       'wifi'),
  ('airbnb','amenity','Fast wifi',                  'wifi'),
  ('airbnb','amenity','Air conditioning',           'air_conditioning'),
  ('airbnb','amenity','Central air conditioning',   'air_conditioning'),
  ('airbnb','amenity','Heating',                    'heating'),
  ('airbnb','amenity','Kitchen',                    'kitchen'),
  ('airbnb','amenity','Kitchenette',                'kitchen'),
  ('airbnb','amenity','Washer',                     'washer'),
  ('airbnb','amenity','Free washer',                'washer'),
  ('airbnb','amenity','TV',                         'tv'),
  ('airbnb','amenity','HDTV',                       'tv'),
  ('airbnb','amenity','Dedicated workspace',        'workspace'),
  ('airbnb','amenity','Pool',                       'pool'),
  ('airbnb','amenity','Private pool',               'pool'),
  ('airbnb','amenity','Hot tub',                    'hot_tub'),
  ('airbnb','amenity','Free parking on premises',   'free_parking'),
  ('airbnb','amenity','Free parking',               'free_parking'),
  ('airbnb','amenity','Gym',                        'gym'),
  ('airbnb','amenity','Exercise equipment',         'gym'),
  ('airbnb','amenity','Balcony',                    'balcony'),
  ('airbnb','amenity','Patio or balcony',           'balcony'),
  ('airbnb','amenity','Garden',                     'garden'),
  ('airbnb','amenity','Backyard',                   'garden'),
  ('airbnb','amenity','BBQ grill',                  'bbq_grill'),
  ('airbnb','amenity','Smoke alarm',                'smoke_alarm'),
  ('airbnb','amenity','Carbon monoxide alarm',      'carbon_monoxide_alarm'),
  ('airbnb','amenity','Fire extinguisher',          'fire_extinguisher'),
  ('airbnb','amenity','First aid kit',              'first_aid_kit'),
  ('airbnb','amenity','Breakfast',                  'breakfast'),
  ('airbnb','amenity','Hot water',                  'hot_water'),
  ('airbnb','amenity','Elevator',                   'elevator')
on conflict (source, entity_type, external_value) do nothing;
